# Generated by Django 3.1.1 on 2020-09-19 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('mbti_result', models.CharField(max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
